version: '3.8'
services:
  kiosk-app:
    build: .
    container_name: angular_kiosk
    ports:
      - "4200:80"
    environment:
      - GRAFANA_URL=http://grafana:3000
    depends_on:
      - grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
