services:
  frontend:
    image: ghcr.io/2324-4bhif-syp/2324-4bhif-syp-project-iot-dashboard/kiosk:latest
    container_name: leoenergy-kiosk
    ports:
      - "8000:80"
    depends_on:
      - influxdb
      - grafana
      - leoenergy
