version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=Leoenergy
      - DOCKER_INFLUXDB_INIT_BUCKET=db
      - DOCKER_INFLUXDB_INIT_RETENTION=20w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=8e447b3e8bbce7d5ceb9321937661420d0503a03361157018e9ec99c9ea251b4
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./data/influxdb2:/var/lib/influxdb2

  influxdb_restore:
    image: influxdb:latest
    container_name: influxdb_restore
    volumes:
      - ./data/influxdb2:/var/lib/influxdb2
      - /home/balint/htl/4bhif/syp/2324-4bhif-syp-project-iot-dashboard/influxdb_backup:/backups
    entrypoint: influxd restore --full --metadata-path /var/lib/influxdb2/meta --data-path /var/lib/influxdb2/engine /backups/backup_20241225_170529
    restart: "no"
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_INIT_ORG: Leoenergy
      INFLUXDB_INIT_BUCKET: db
      INFLUXDB_INIT_ADMIN_TOKEN: 8e447b3e8bbce7d5ceb9321937661420d0503a03361157018e9ec99c9ea251b4
