services:
  leoenergy:
    image: ghcr.io/2324-4bhif-syp/2324-4bhif-syp-project-iot-dashboard/leoenergy:latest
    container_name: leoenergy
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
      - grafana
