services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment: # <1>
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=Leoenergy
      - DOCKER_INFLUXDB_INIT_BUCKET=db
      - DOCKER_INFLUXDB_INIT_RETENTION=20w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=8e447b3e8bbce7d5ceb9321937661420d0503a03361157018e9ec99c9ea251b4
    ports:
      - "8086:8086"
    volumes: # <2>
      - ./data/influxdb:/var/lib/influxdb
      - ./data/influxdb2:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    volumes: # <3>
      - ./data/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    user: "${UID}:${GID}"
    depends_on:
      - influxdb

  leoenergy:
    image: ghcr.io/2324-4bhif-syp/2324-4bhif-syp-project-iot-dashboard/leoenergy:latest
    container_name: leoenergy-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
      - grafana

  frontend:
    image: ghcr.io/2324-4bhif-syp/2324-4bhif-syp-project-iot-dashboard/kiosk:latest
    container_name: leoenergy-kiosk
    ports:
      - "8000:80"
    depends_on:
      - influxdb
      - grafana
      - leoenergy
