version: "3"
services:
  postgres-db:
    image: postgres:15.2-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    volumes:
      - $PWD/data/db-postgres/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - $PWD/data/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana-enterprise
    user: "1000"
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana